version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    working_directory: ~/react-ssr-starter
    steps:
      - run:
          name: Install yarn
          command: sudo npm install -g yarn
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: Build Docker image
          command: yarn docker:build:ci
      - run:
          name: Start Docker container
          command: docker run -d --name ssr ssr-production tail -f /dev/null
      - run:
          name: Lint JS
          command: docker exec ssr yarn lint:js:ci
          when: always
      - run:
          name: Lint CSS
          command: docker exec ssr yarn lint:css:ci
          when: always
      - run:
          name: Run tests
          command: docker exec ssr yarn test:ci
          when: always
      - run:
          name: Retrieve artifacts from Docker container
          command: docker cp ssr:react-ssr-starter/artifacts ./artifacts
          when: always
      - store_artifacts:
          path: artifacts
      - store_test_results:
          path: artifacts/test_results
