version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    working_directory: ~/react-ssr-starter
    steps:
      - run:
          name: Install yarn
          command: sudo npm install -g yarn

      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: yarn docker:build:production

      - run:
          name: Run linter
          command: |
            docker run -d --name ssr ssr-production
            docker exec ssr yarn lint

      - run:
          name: Run tests
          command: |
            docker run -d --name ssr ssr-production
            docker exec ssr yarn test
