version: '3.0'

services:
  mash:
    build:
      context: ../..
      dockerfile: internals/docker/dev.Dockerfile
    command: yarn start
    container_name: mash-dev-server
    image: mash-dev
    ports:
      - 3000:3000
    volumes:
      - mash-sync:/mash:nocopy

volumes:
  mash-sync:
    external: true
