version: '3.0'

services:
  ssr:
    build:
      context: ../..
      dockerfile: internals/docker/dev.Dockerfile
    command: yarn start
    container_name: ssr-dev-server
    image: ssr-dev
    ports:
      - 3000:3000
    volumes:
      - ssr-sync:/react-ssr-starter:nocopy

volumes:
  ssr-sync:
    external: true
